import Head from "next/head";
import Image from "next/image";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <nav>
        <Image src="/arrow-left.svg" width={15} height={24} alt="" />
        <Image src="/spacex-logo.svg" width={300} height={36} alt="" />
        <Image src="/arrow-right.svg" width={15} height={24} alt="" />
      </nav>
      <main></main>
    </div>
  );
}
